apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nyx-prod
commonLabels:
  app.kubernetes.io/instance: nyx-prod
resources:
  - namespace.yaml
  - ../../base
  - pdb.yaml
patches:
  - path: patches/deployment-prod.yaml
  - path: patches/configmap-prod.yaml
